common:
    runtime: rpiwcl.cos.runtime.SalsaRuntime
    terminal: rpiwcl.cos.runtime.GnomeTerminal
    cpumark_per_runtime: 2000
    base_runtime_port: 4040

launcher_port: 49152

cos:
    launch_spec:
#        ipaddr: 128.213.23.13
        ipaddr: localhost
        port: 49153
#        user: imais
        user: shigeru
        terminal_profile: Blue
        main_class: rpiwcl.cos.cosmanager.CosManager
        classpath: /home/shigeru/Git/COS/classes:/home/shigeru/Git/COS/lib/jyaml-1.3.jar
    runtime_conf:
        policy: deadline-30min
        # policy: budget-10USD
        reconfiguration: cos
        #reconfiguration: ios
        clouds:
            - cloud-rpiwcl
            - cloud-aws

# private cloud
cloud-rpiwcl:
    launch_spec:
#        ipaddr: 128.213.23.13
        ipaddr: localhost
        port: 49154
#        user: imais
        user: shigeru
        terminal_profile: Purple
        main_class: rpiwcl.cos.cloud.PrivateCloudController
        classpath: ~/Git/COS/classes
        parent: cos
    runtime_conf:
        type: private
        nodes:
            - node-nimbus
            - node-cirrus
node-nimbus:
    launch_spec:
        ipaddr: 128.213.23.13
        port: 49155
        user: imais
        terminal_profile: Purple
        main_class: rpiwcl.cos.node.NodeController
        classpath: ~/Git/COS/classes
        parent: cloud-rpiwcl
    runtime_conf:
        vm_support: no
        vm_user: ubuntu
        vm_image: /home/xen/domains/ubuntu/ubuntu.img
node-cirrus:
    launch_spec:
        ipaddr: 128.213.23.12
        port: 49155
        user: imais
        terminal_profile: Purple
        main_class: rpiwcl.cos.node.NodeController
        classpath: ~/Git/COS/classes
        parent: cloud-rpiwcl
    runtime_conf:
        vm_support: no
        vm_user: ubuntu
        vm_image: /home/xen/domains/ubuntu/ubuntu.img

# public cloud
cloud-aws:
    launch_spec:
#        ipaddr: 128.213.23.13
        ipaddr: localhost
        port: 49156
#        user: imais
        user: shigeru
        terminal_profile: Green
        main_class: rpiwcl.cos.cloud.AmazonEC2Controller
        classpath: ~/Git/COS/classes
        parent: cos
    runtime_conf:
        type: public
        vm_cost_per_hour: 0.48USD
        vm_instance_ids: 
            - i-da6431b2
            - i-e1cd058c
            - i-d68e84bf
            - i-db1892b3
            - i-65cfc407

       












