common:
    app_runtime: rpiwcl.cos.runtime.SalsaRuntime
    app_runtime_cp: &app-runtime-cp /home/shigeru/Git/COS/cos-0.3.jar:/home/shigeru/Git/COS/lib/salsa/salsa1.1.5.jar
    app_base_port: &app-base-port 4040
    app_option: &app-option -Dnetif=eth0
    terminal: rpiwcl.cos.runtime.GnomeTerminal
    cpumark_per_runtime: 1000
    base_runtime_port: 4040
    classpath: &cp /home/shigeru/Git/COS/cos-0.3.jar:/home/shigeru/Git/COS/lib/jyaml-1.3.jar:/home/shigeru/Git/COS/lib/Jama-1.0.3.jar:/home/shigeru/Git/COS/lib/aws-java-sdk-1.5.0/lib/*:/home/shigeru/Git/COS/lib/aws-java-sdk-1.5.0/third-party/commons-codec-1.3/*:/home/shigeru/Git/COS/lib/aws-java-sdk-1.5.0/third-party/commons-logging-1.1.1/*:/home/shigeru/Git/COS/lib/aws-java-sdk-1.5.0/third-party/httpcomponents-client-4.2.3/*
    priv_vm_image: &vm-image /home/xen/domains/ubuntu/ubuntu.img
    priv_use_vm: &use-vm false

prices:
    t1.micro: 0.02
    m1.small: 0.06
    m1.medium: 0.12
    m1.large: 0.24 
    m1.xlarge: 0.48 
    m3.xlarge: 0.50 
    m3.2xlarge: 1.00 
    c1.medium: 0.145 
    c1.xlarge: 0.58 
    cc2.8xlarge: 1.30 

starter_port: 49152

cos:
    launch_spec:
        ipaddr: &cos-ipaddr 10.0.2.15
        port: &cos-port 49153
        user: shigeru
        terminal_profile: Blue
        main_class: rpiwcl.cos.manager.CosManager
        classpath: *cp
    runtime_conf:
        ipaddr: *cos-ipaddr
        port: *cos-port
        initial_num_runtimes: 1
        policy: deadline=15-sec
        reconfiguration: true
        ec2_runtimes_per_instance: *ec2-runtimes-per-instance
        ec2_instance_type: *ec2-instance-type
        private_clouds:
            - cloud-rpiwcl
        public_clouds:			
            - cloud-ec2

# private cloud
cloud-rpiwcl:
    launch_spec:
        ipaddr: localhost
        port: 49154
        user: shigeru
        terminal_profile: Purple
        main_class: rpiwcl.cos.cloud.PrivCloudController
        classpath: *cp
        parent: cos
    runtime_conf:
        nodes:
            - node-nimbus
            - node-cirrus
node-nimbus:
    launch_spec:
        ipaddr: &node-nimbus-ipaddr localhost
        port: 49155
        user: &node-nimbus-user shigeru
        terminal_profile: Purple
        main_class: rpiwcl.cos.node.NodeController
        classpath: *cp
        parent: cloud-rpiwcl
    runtime_conf:
        app_runtime:
            ipaddr: *node-nimbus-ipaddr
            user: *node-nimbus-user
            terminal_profile: Red
            main_class: wwc.messaging.Theater
            classpath: *app-runtime-cp
            base_port: *app-base-port
            app_option: *app-option
            parent: node-nimbus
        use_vm: *use-vm
        vm_support: true
        vm_user: ubuntu
        vm_image: *vm-image
node-cirrus:
    launch_spec:
        ipaddr: &node-cirrus-ipaddr localhost
        port: 49156
        user: &node-cirrus-user shigeru
        terminal_profile: Purple
        main_class: rpiwcl.cos.node.NodeController
        classpath: *cp
        parent: cloud-rpiwcl
    runtime_conf:
        app_runtime:
            ipaddr: *node-cirrus-ipaddr
            user: *node-cirrus-user
            terminal_profile: Red
            main_class: wwc.messaging.Theater
            classpath: *app-runtime-cp
            base_port: 4140
            app_option: *app-option
            parent: node-cirrus
        use_vm: *use-vm
        vm_support: true
        vm_user: ubuntu
        vm_image: *vm-image

# public cloud
cloud-ec2:
    launch_spec:
        ipaddr: localhost
        port: 49157
        user: shigeru
        terminal_profile: Green
        main_class: rpiwcl.cos.cloud.AmazonEC2Controller
        classpath: *cp
        parent: cos
    runtime_conf:
        app_runtime:
            ipaddr: null
            ssh_option: -i /home/shigeru/.ssh/wclcloud.pem -o StrictHostKeyChecking=yes
            user: ubuntu
            terminal_profile: Red
            main_class: wwc.messaging.Theater
            classpath: /home/ubuntu/Git/COS/cos-0.3.jar:/home/ubuntu/Git/COS/lib/salsa/salsa1.1.5.jar
            base_port: *app-base-port
            app_option: -Dnetif=eth0 -Dextip
            parent: cloud-ec2
        ec2_credential_file: AwsCredentials.properties
        ec2_security_group: quick-start-1
        ec2_runtimes_per_instance: 1
        ec2_instance_type: m1.small
        ec2_image_id: ami-4a582623
        ec2_key_name: wclcloud
        ec2_availability_zone: us-east-1d



       












