common:
    app_runtime: rpiwcl.cos.runtime.SalsaRuntime
    app_runtime_cp: &app-runtime-cp /home/shigeru/Git/COS/cos-0.3.jar:/home/shigeru/Git/COS/lib/salsa/salsa1.1.5.jar
    app_base_port: &app-base-port 4040
    app_option: &app-option -Dnetif=eth0
    terminal: rpiwcl.cos.runtime.GnomeTerminal
    cpumark_per_runtime: 1000
    base_runtime_port: 4040
    classpath: &cp /home/shigeru/Git/COS/cos-0.3.jar:/home/shigeru/Git/COS/lib/jyaml-1.3.jar:/home/shigeru/Git/COS/lib/Jama-1.0.3.jar
    vm_image: &vm-image /home/xen/domains/ubuntu/ubuntu.img
    vm_cost_per_hour: 0.48USD
    use_vm: &use-vm false

starter_port: 49152

cos:
    launch_spec:
        ipaddr: &cos-ipaddr 10.0.2.15
        port: &cos-port 49153
        user: shigeru
        terminal_profile: Blue
        main_class: rpiwcl.cos.manager.CosManager
        classpath: *cp
    runtime_conf:
        ipaddr: *cos-ipaddr
        port: *cos-port
        initial_num_runtimes: 1
        policy: deadline=15-sec
        reconfiguration: cos
        private_clouds:
            - cloud-rpiwcl
        public_clouds:			
            - cloud-aws

# private cloud
cloud-rpiwcl:
    launch_spec:
        ipaddr: localhost
        port: 49154
        user: shigeru
        terminal_profile: Purple
        main_class: rpiwcl.cos.cloud.PrivCloudController
        classpath: *cp
        parent: cos
    runtime_conf:
        nodes:
            - node-nimbus
            - node-cirrus
node-nimbus:
    launch_spec:
        ipaddr: &node-nimbus-ipaddr localhost
        port: 49155
        user: &node-nimbus-user shigeru
        terminal_profile: Purple
        main_class: rpiwcl.cos.node.NodeController
        classpath: *cp
        parent: cloud-rpiwcl
    runtime_conf:
        app_runtime:
            ipaddr: *node-nimbus-ipaddr
            user: *node-nimbus-user
            terminal_profile: Red
            main_class: wwc.messaging.Theater
            classpath: *app-runtime-cp
            base_port: *app-base-port
            option: *app-option
            parent: node-nimbus
        use_vm: *use-vm
        vm_support: true
        vm_user: ubuntu
        vm_image: *vm-image
node-cirrus:
    launch_spec:
        ipaddr: &node-cirrus-ipaddr localhost
        port: 49156
        user: &node-cirrus-user shigeru
        terminal_profile: Purple
        main_class: rpiwcl.cos.node.NodeController
        classpath: *cp
        parent: cloud-rpiwcl
    runtime_conf:
        app_runtime:
            ipaddr: *node-cirrus-ipaddr
            user: *node-cirrus-user
            terminal_profile: Red
            main_class: wwc.messaging.Theater
            classpath: *app-runtime-cp
            base_port: 4140
            option: *app-option
            parent: node-cirrus
        use_vm: *use-vm
        vm_support: true
        vm_user: ubuntu
        vm_image: *vm-image

# public cloud
cloud-aws:
    launch_spec:
        ipaddr: localhost
        port: 49157
        user: shigeru
        terminal_profile: Green
        main_class: rpiwcl.cos.cloud.AmazonEC2Controller
        classpath: *cp
        parent: cos
    runtime_conf:
        vm_instance_ids: 
            - i-da6431b2
            - i-e1cd058c
            - i-d68e84bf
            - i-db1892b3
            - i-65cfc407

       












