common:
    runtime: rpiwcl.cos.runtime.SalsaRuntime
    terminal: rpiwcl.cos.runtime.GnomeTerminal
    cpumark_per_runtime: 2000
    base_runtime_port: 4040
    classpath: &cp /home/shigeru/Git/COS/cos-0.3.jar:/home/shigeru/Git/COS/lib/jyaml-1.3.jar
    vm_image: &vm-image /home/xen/domains/ubuntu/ubuntu.img
    vm_cost_per_hour: &vm-cost-per-hour 0.48USD
    use_vm: &use-vm false

launcher_port: 49152

cos:
    launch_spec:
        ipaddr: localhost
        port: 49153
        user: shigeru
        terminal_profile: Blue
        main_class: rpiwcl.cos.cosmanager.CosManager
        classpath: *cp
    runtime_conf:
        policy: deadline-30min
        # policy: budget-10USD
        reconfiguration: cos
        #reconfiguration: ios
        clouds:
            - cloud-rpiwcl
            - cloud-aws

# private cloud
cloud-rpiwcl:
    launch_spec:
        ipaddr: localhost
        port: 49154
        user: shigeru
        terminal_profile: Purple
        main_class: rpiwcl.cos.cloud.PrivCloudController
        classpath: *cp
        parent: cos
    runtime_conf:
        type: private
        nodes:
            - node-nimbus
            - node-cirrus
node-nimbus:
    launch_spec:
        ipaddr: localhost
        port: 49155
        user: shigeru
        terminal_profile: Purple
        main_class: rpiwcl.cos.node.NodeController
        classpath: *cp
        parent: cloud-rpiwcl
    runtime_conf:
        use_vm: *use-vm
        vm_support: true
        vm_user: ubuntu
        vm_image: *vm-image
node-cirrus:
    launch_spec:
        ipaddr: localhost
        port: 49156
        user: shigeru
        terminal_profile: Purple
        main_class: rpiwcl.cos.node.NodeController
        classpath: *cp
        parent: cloud-rpiwcl
    runtime_conf:
        use_vm: *use-vm
        vm_support: true
        vm_user: ubuntu
        vm_image: *vm-image

# public cloud
cloud-aws:
    launch_spec:
        ipaddr: localhost
        port: 49157
        user: shigeru
        terminal_profile: Green
        main_class: rpiwcl.cos.cloud.AmazonEC2Controller
        classpath: *cp
        parent: cos
    runtime_conf:
        type: public
        vm_cost_per_hour: *vm-cost-per-hour
        vm_instance_ids: 
            - i-da6431b2
            - i-e1cd058c
            - i-d68e84bf
            - i-db1892b3
            - i-65cfc407

       












